CREATE TABLE animes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name text NOT NULL UNIQUE
);

CREATE TABLE characters (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name text NOT NULL UNIQUE,
	anime_id INTEGER,
	image text,
	FOREIGN KEY(anime_id) REFERENCES animes(id) ON DELETE CASCADE ON UPDATE CASCADE
);
